# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "raytracing"
version = "0.1.0"
edition = "2018"

[lib]
name = "mylib"
path = "src/lib.rs"

[dependencies]
